import { UserProvider } from '@auth0/nextjs-auth0/client';
import type { Metadata } from 'next';
import { Outfit } from 'next/font/google';
import { ConversationProvider } from '../context/conversation';
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import './globals.css';

config.autoAddCss = false;

const outfit = Outfit({
	subsets: ['latin'],
	variable: '--font-outfit',
});

export const metadata: Metadata = {
	title: 'PAI - GPT',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<link rel="icon" href="favicon.png" sizes="any" />
			</head>
			<UserProvider>
				<ConversationProvider>
					<body className={`${outfit.variable} antialiased`}>{children}</body>
				</ConversationProvider>
			</UserProvider>
		</html>
	);
}
